## Carga de archivos

Basado en: "Python for data analysis" de Wes Mckinney y https://github.com/AdityaGogoi/Notes-on-Python-for-Data-Analysis-2nd-Edition

## Introducción

La primera parte de cualquier flujo de código de análisis de datos es la carga de los datos. Esto puede ocurrir de varias formas diversas: archivos textuales (csv, txt), archivos de excel, páginas web (html), API, bases de datos, etc.

### Lectura de datos en formatos planos de texto (csv, txt)
Empecemos explorando los archivos planos de texto, el tipo de archivo más básico. Veamos como se procesan y cargan.

In [1]:
### !type ejecuta en cmd "type" lo cual imprime los contenidos del archivo
!type examples\ex1.csv

a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

Con read_csv de pandas ya sabemos cargar un csv.

In [2]:
import pandas as pd

df = pd.read_csv('examples/ex1.csv')
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

Podemos también decirle a pandas que lo lea sin encabezados o darle los nuestros.

In [3]:
! type examples\ex2.csv

1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [4]:
pd.read_csv('examples/ex2.csv', header=None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [5]:
pd.read_csv('examples/ex2.csv', names=['a','b','c','d','message'])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

Podemos especificar una cierta columna como el indice de la tabla, en este caso, "message".

In [6]:
names = ['a','b','c','d','message']
pd.read_csv('examples/ex2.csv', names=names, index_col='message')

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

A veces es necesario especificar otro separador.

In [7]:
result = pd.read_table('examples/ex3.txt', sep='\s+')
result

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

Ejercicio: cargue de forma adecuada los datos de la tabla de ex4.csv. Note que las columnas están en la segunda fila, y el contenido a partir de la quinta.

In [8]:
!type examples\ex4.csv

# hey!
a,b,c,d,message
# just wanted to make things more difficult for you
# who reads CSV files with computers, anyway?
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [9]:
# Solucion


La opción "max_rows" ajusta cuantas lineas imprimirá Jupyter.

También podemos usar 'nrows' para leer solo cierto número de filas.

In [10]:
pd.options.display.max_rows = 4

result = pd.read_csv('examples/ex6.csv')
result

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
...        ...       ...       ...       ...  ..
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [11]:
pd.read_csv('examples/ex6.csv',nrows=4)

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R

### Exportar a un archivo

Con el método "to_csv" exportamos nuestro dataframe a un archivo csv. Podemos usar el separador que queramos.

In [12]:
data = pd.read_csv('examples/ex5.csv')

data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [13]:
## esto lo crea en la carpeta donde esta el notebook en "examples"
data.to_csv('examples/out.csv', sep='|')

In [14]:
!type examples\out.csv

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo

In [15]:
### Podemos indicar que los nulos no los deje vacíos sino que ponga el valor "NULL"
data.to_csv('examples/out.csv', sep=';', na_rep='NULL')

!type examples\out.csv

;something;a;b;c;d;message
0;one;1;2;3.0;4;NULL
1;two;5;6;NULL;8;world
2;three;9;10;11.0;12;foo

Por defecto se escriben los índices y los encabezados. Pero los podemos desactivar con la siguiente opción:

In [16]:
data.to_csv('examples/out.csv',index=False, header=False)

### JSON

JSON (JavaScript Object Notation) se ha vuelto uno de los formatos más comunes para enviar datos en navegadores, APIs, etc; además de para almacenarlos en bases de datos semiestructuradas de tipo documento.
 
Ejemplo de json:

https://techeplanet.com/json-example/

El formato json es mucho más libre que el csv.

Hay muchas librerías para trabajar con json. Una es la librería "json": con json.loads podemos convertir un JSON string a un diccionario. Para la operación inversa, se usa json.dumps.

Si le pasamos una lista de json a un objeto Dataframe, se construirá una dataframe usando todos esos json, siempre y cuando todos los objetos tengan la misma longitud.

In [17]:
obj = """
{"name": "Wes",
 "places_lived": ["United States", "Spain", "Germany"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},
              {"name": "Katie", "age": 38,
               "pets": ["Sixes", "Stache", "Cisco"]}]
}
"""

In [18]:
obj

'\n{"name": "Wes",\n "places_lived": ["United States", "Spain", "Germany"],\n "pet": null,\n "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},\n              {"name": "Katie", "age": 38,\n               "pets": ["Sixes", "Stache", "Cisco"]}]\n}\n'

In [19]:
import json

result = json.loads(obj)
result

{'name': 'Wes',
 'places_lived': ['United States', 'Spain', 'Germany'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 30, 'pets': ['Zeus', 'Zuko']},
  {'name': 'Katie', 'age': 38, 'pets': ['Sixes', 'Stache', 'Cisco']}]}

In [20]:
type(result)

dict

In [21]:
asjson = json.dumps(result)
asjson

'{"name": "Wes", "places_lived": ["United States", "Spain", "Germany"], "pet": null, "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]}, {"name": "Katie", "age": 38, "pets": ["Sixes", "Stache", "Cisco"]}]}'

In [22]:
type(asjson)

str

In [23]:
### Si elijo el campo siblings del json, me permite convertirlo a dataframe
siblings = pd.DataFrame(result['siblings'])
siblings

    name  age                    pets
0  Scott   30            [Zeus, Zuko]
1  Katie   38  [Sixes, Stache, Cisco]

Ojo con los bloques try except! Es mala práctica dejarlo abierto como el siguiente; siempre se debe especificar el error.

In [24]:
## Pero notar que ocurre si le paso todo el json

### Esto es mala practica
try:
    pd.DataFrame(result)
except: 
    print('Algún error, ni idea cual')

Algún error, ni idea cual

In [25]:
### Esto es un poco mas pasable
try:
    pd.DataFrame(result)
except ValueError: 
    print('Value error')

Value error

'pandas.read_json' puede leer automáticamente json y convertirlo a dataframe.

Por defecto se asume que cada objeto del json es una fila de la tabla.

In [26]:
!type examples\example.json

[{"a": 1, "b": 2, "c": 3},
 {"a": 4, "b": 5, "c": 6},
 {"a": 7, "b": 8, "c": 9}]

In [27]:
data = pd.read_json('examples/example.json')
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

Ejercicio: cargue el archivo example2.txt, el cual es un json, usando pandas. Luego, condicionalmente deje solamente aquellas filas de los mayores de 30 años.

Pista: https://stackoverflow.com/questions/53974014/parsing-nested-json-with-pandas


<!---
examp2 =  pd.read_json('examples/example2.txt')
dft = examp2.members.apply(pd.Series)
examp2[dft.columns] = dft
examp2[examp2['age']>30]
-->

### HTML : Web Scraping

Hay varias librerías para procesar datos de html (páginas web), y es común tener que utilizar diferentes tipos de scrapers para extraer información de páginas web. HTML es el formato más común para páginas web.

Panda tiene la función "read_html", la cual usa las librerías lxml y BeautifulSoup para procesar un html como un dataframe.

Por defecto, busca tags de "table" en el html para convertirlas.

In [28]:
import pandas as pd
## Abrirlo en el navegador y comparar. Abrirlo tambien con block de notas
tables = pd.read_html('examples/fdic_failed_bank_list.html')
len(tables)

1

In [29]:
failures = tables[0]
failures.head()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
...,...,...,...,...,...,...,...
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016"
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016"

In [30]:
## Contar filas por año
close_timestamps = pd.to_datetime(failures['Closing Date'])
close_timestamps.dt.year.value_counts()

2010    157
2009    140
       ...
2003      3
2000      2
Name: Closing Date, Length: 15, dtype: int64

## Formatos binarios

La forma más fácil de almacenar objetos de python de forma binaria es mediante "serialización", usando la librería pickle. La forma binaria es muy "cruda" y pura para el computador, por lo que será mas eficiente (menos espacio). Pero para nosotros no sera entendible (intentar abrir un pickle con notepad.).

Podemos guardar un objeto de pandas como un pickle (binario) usando to_pickle, y leerlo usando read_pickle. Tener en cuenta que, según la versión de pickle que se use, un objeto podría luego poner problemas para cargarse a futuro, si la versión de pickle cambia.

In [31]:
frame = pd.read_csv('examples/ex1.csv')
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [32]:
frame.to_pickle('examples/frame_pickle')

In [33]:
pd.read_pickle('examples/frame_pickle')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [34]:
datafp = pd.read_pickle('examples/frame_pickle')
datafp

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [35]:
from sklearn.linear_model import LinearRegression

In [36]:
reg_lineal = LinearRegression()

In [37]:
X= datafp[['a','b','c']]
X

   a   b   c
0  1   2   3
1  5   6   7
2  9  10  11

In [38]:
y = datafp['d']
y

0     4
1     8
2    12
Name: d, dtype: int64

In [39]:
reg_lineal.fit(X,y)

LinearRegression()

In [40]:
reg_lineal.predict(X)

array([ 4.,  8., 12.])

In [41]:
# save the model to disk
import pickle
filename = 'examples/finalized_model.sav'
pickle.dump(reg_lineal, open(filename, 'wb'))

In [42]:
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))

In [43]:
loaded_model.predict(X)

array([ 4.,  8., 12.])

Otro formato binario muy usado es el formato "parquet", el cual se usa en varios distintos lenguajes y herramientas para almacenar los datos. Este formato binario es muy eficiente con su manejo de espacio, lo cual lo hace muy útil para grandes cantidades de datos.

Esta tarea de guardar en binario para comprimir los datos se vuelve necesaria cuando tenemos demasiados conjuntos de datos para guardar en disco.

In [44]:
d6 = pd.read_csv('examples/ex6.csv')
d6

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
...        ...       ...       ...       ...  ..
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [45]:
d6.to_csv('examples/d6.csv', index=False)

In [46]:
d6.to_parquet('examples/d6.parquet', index=False)

In [47]:
d6n = pd.read_parquet('examples/d6.parquet')
d6n

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
...        ...       ...       ...       ...  ..
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

Note la diferencia en tamaño entre el csv y el parquet en el explorador de archivos.

### Microsoft Excel


Pandas permite leer archivos de Excel 2003 en adelante usando "pandas.read_excel". Por dentro pandas usa las librerias xlrd y openpyxl para leer los archivos xls y xlsx respectivamente.

Podemos elegir también la hoja a cargar.

Además, con el método "to_excel", podemos exportar el dataframe a Excel.

Ejercicio: cargue los datos del archivo ex2.xlsx en un dataframe, y luego expórtelos a un archivo ex3.xlsx que sea idéntico a ex2.xlsx en la hoja de datos (no necesariamente en la otra hoja).

### APIs [opcional para el curso]

Muchos sitios web tienen APIs públicas para proveer data mediante Json u otros formatos. 

Hay muchas formas de interactuar con ellas, una es con la librería "requests". 

En este ejemplo, encontramos los últimos 30 issues de github de pandas.

La respuesta incluirá objetos json.

Cada elemento en la respuesta es un diccionario que contiene todo lo encontrado en Github.

Podemos leer esto con pandas para analizarlo.

In [48]:
import requests

url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp ## 200 es respuesta correcta

In [49]:
data = resp.json()
data[0]['title'] ### Titutlo del primer issue

'DEPS: Bump Meson, lower pin Cython'

In [50]:
### uso pandas para cargar los json, indicandole las columnas que quiero conservar y el string json que recibi de request
issues = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
issues.head()

,number,title,labels,state
0,62086,"DEPS: Bump Meson, lower pin Cython","[{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...",open
1,62085,BUG: Preserve column names in DataFrame.from_r...,[],open
...,...,...,...,...
3,62083,BUG: Preserve full float precision when double...,[],open
4,62082,DOC: clarify Series alignment when assigning t...,[],open

In [51]:
issues

,number,title,labels,state
0,62086,"DEPS: Bump Meson, lower pin Cython","[{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...",open
1,62085,BUG: Preserve column names in DataFrame.from_r...,[],open
...,...,...,...,...
28,62033,BUG: Wrong inferred type in case of a mixture ...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
29,62031,API: timestamp resolution inference: default t...,"[{'id': 211840, 'node_id': 'MDU6TGFiZWwyMTE4ND...",open

### Bases de datos

Las bases de datos relacionales basadas en SQL son muy comunes para almacenar datos (SQL Server, MySQL, etc).

Cargar datos desde una base de datos SQL a un dataframe es sencillo, pandas nos permite hacerlo sin mayor problema.

Vamos a crear una base de datos SQLite usando el driver sqlite3 de Python.

In [52]:
import sqlite3

import time
nombre_tabla_unico = "test" + str(int(time.time())  )

# Notar que uso una f-string para reemplazar el valor de la variable en la string
query = f"""
CREATE TABLE {nombre_tabla_unico}
(a VARCHAR(20), b VARCHAR(20),
c REAL, d INTEGER);
"""
### declaro Dos variables varchar, una real (float), y una entera)

## Y establezco la conexiona a la base de datos mydata para crear la tabla test1

con = sqlite3.connect('examples/mydata.sqlite')
con.execute(query)
con.commit()

In [53]:
### Agrego 4 filas a la tabla con un query
data = [('Atlanta', 'Georgia', 1.25, 6),
        ('Tallahassee', 'Florida', 2.6, 3),
        ('Albany', 'New York', 3, 2),
        ('Sacramento', 'California', 1.7, 5)]

stmt = f"INSERT INTO {nombre_tabla_unico} VALUES(?,?,?,?)"

con.executemany(stmt, data)

In [54]:
# commit para confirmar los querys y cambios realizados
con.commit()


La mayoria de los drivers retornan una lista de tuplas cuando uso un Select.

Podemos usar estas listas de tuplas para el Dataframe.

In [55]:
### Traer todas las filas
cursor = con.execute('select * from ' + nombre_tabla_unico)
rows = cursor.fetchall()
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Albany', 'New York', 3.0, 2),
 ('Sacramento', 'California', 1.7, 5)]

In [56]:
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2       Albany    New York  3.00  2
3   Sacramento  California  1.70  5


Para ahorrarnos gran parte de estas lineas de codigo (la conexion, los commit, etc), podemos usar SQLAlchemy, la cual concilia varias diferencias entre bases de datos SQL. Con esta librería, podemos luego usar pandas.read_sql para leer directamente la query que queramos y generar la tabla.

In [57]:
import sqlalchemy as sqla

db = sqla.create_engine('sqlite:///examples/mydata.sqlite')
tabla=pd.read_sql('select * from ' + nombre_tabla_unico, db)

In [58]:
tabla

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2       Albany    New York  3.00  2
3   Sacramento  California  1.70  5

Por ejemplo, el siguiente ejemplo muestra como podemos usar un query de SQL para traer el estado cuya capital es Tallahassee.


Note las 3 partes principales del query de SQL: el "Select" (que sirve para ver que columnas queremos traer), el "FROM" (que referencia la tabla de la cual queremos extraer los datos), y el WHERE (que indica cuáles con las condiciones que queremos que cumplan los datos que traeremos).

In [59]:
# Aqui construyo el query de SQL que quiero ejecutar, usando el nombre de la tabla que había creado (el
# cual esta guardado en la variable "nombre_tabla_unico")
query_ejemplo = "SELECT b FROM " + nombre_tabla_unico + " WHERE a='Tallahassee';"
print(query_ejemplo)

SELECT b FROM test1754884790 WHERE a='Tallahassee';

In [60]:
# Ejecutar el query con  la conexion a la base de datos y mostrar el resultado
tabla=pd.read_sql(query_ejemplo, db)
tabla

         b
0  Florida

##### Ejercicio: 

Cree un dataframe donde deje solo el nombre del estado y de la capital de las filas con un valor de c mayor a 1.5 y un valor de d menor a 4, usando un query de SQL.


<details><summary> Solucion (dar click para editar)</summary>
<p>

db = sqla.create_engine('sqlite:///examples/mydata.sqlite')
tabla=pd.read_sql(f'select a,b from {nombre_tabla_unico} where c>1.5 and d<4', db)
tabla

</p>
</details>

### Ejemplo de big data [opcional para el curso]
Calcular la media del siguiente dataframe.

In [61]:
## Este dataset se puede demorar varios minutos generandose. Poner por ejemplo 30k filas y 3k columnas si 
# quieren algo que ya empiece a ser bien pesado (1.5gb)
# Si ya lo quieren ver colapsar, generar un archivo de 5 o 6 gb (en pc de 8 ram). o sea como 4 veces mas grande
import pandas as pd
import numpy as np
from os import path
n_rows = 300 ## Aumentarlo lo que deseen
n_cols = 3000
for i in range(1, 2):
    df = pd.DataFrame(np.random.uniform(0, 100, size=(n_rows, n_cols)), columns=['col%d' % i for i in range(n_cols)])
    df.to_csv("analisis.csv", index=False)
df.head()

,col0,col1,col2,col3,col4,col5,col6,col7,col8,col9,...,col2990,col2991,col2992,col2993,col2994,col2995,col2996,col2997,col2998,col2999
0,85.874401,69.176200,82.197289,73.034556,1.952192,15.929606,83.825251,32.745882,67.198640,77.231149,...,39.199696,97.002866,83.025015,57.205656,11.993109,36.827508,63.987150,22.277468,40.697103,97.919797
1,23.211023,58.480628,60.881938,68.764832,88.241653,13.118442,70.534495,84.889804,52.612764,32.049050,...,93.783145,65.987145,97.050286,9.493845,17.598317,63.315218,95.491151,64.724060,20.295733,78.736354
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3,23.616173,22.830682,47.445257,52.113704,60.768414,1.916206,90.108005,57.006942,24.808994,41.143071,...,53.771987,11.215494,76.952752,30.727131,27.083296,43.444838,66.816786,54.955822,46.711906,42.705882
4,24.816540,81.885699,81.063598,46.814840,98.855837,5.420048,5.488301,15.000554,66.425952,34.513137,...,45.221787,19.770470,78.810867,37.171424,4.248523,57.725059,54.489365,89.146227,72.962439,69.763238

In [62]:
df.mean()

col0       49.782518
col1       48.087470
             ...
col2998    50.843657
col2999    51.489741
Length: 3000, dtype: float64

In [63]:
df.mean().mean()

50.05919383294176

In [64]:
df.shape

(300, 3000)

Notar como empieza a poner problema.

### Comparar memoria consumida de ambas formas (mirar el admin de tareas)
Reiniciar el kernel antes de correr los siguientes pasos.

In [65]:
import pandas as pd

In [66]:
### Cargar el df y calcular la media
newdf = pd.read_csv('analisis.csv')
newdf.mean().mean()

50.05919383294176

Mejor cargarlo por chunks (reiniciar de nuevo el kernel antes de esto):

In [67]:
import pandas as pd
sum_vals, counter = 0, 0
for df in pd.read_csv("analisis.csv", chunksize=5000):
    sum_vals += df.sum().sum()
    counter += df.count().sum()
print (sum_vals/counter)

50.059193832941865